apiVersion: batch/v1
kind: Job
metadata:
  name: dns-test
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: hello
          image: orvice/dns-test
          command:
            [
              "/app/dns-test",
              "-host",
              "redis.db",
              "-c",
              "200",
              "-d",
              "30",
              "-l",
              "5000",
            ]
      restartPolicy: Never
      imagePullPolicy: Always
      dnsConfig:
        options:
          - name: single-request-reopen
